-- public schema

-- !Ups

CREATE TABLE public.messages (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ) PRIMARY KEY,
    content text NOT NULL,
    receiver text NOT NULL,
    read boolean NOT NULL
);

CREATE TABLE public.users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ) PRIMARY KEY,
    username text NOT NULL,
    password text NOT NULL
);

-- Username: ?, Password: test
INSERT INTO public.users (username, password) VALUES ('Milenko', '$2a$10$tdBXWNyNDnp0HbnjWtK3g./HquMyK8WUH9sWr937J9AAwW1kIrs3G');
INSERT INTO public.users (username, password) VALUES ('Mihailo', '$2a$10$tdBXWNyNDnp0HbnjWtK3g./HquMyK8WUH9sWr937J9AAwW1kIrs3G');
INSERT INTO public.users (username, password) VALUES ('Tamara', '$2a$10$tdBXWNyNDnp0HbnjWtK3g./HquMyK8WUH9sWr937J9AAwW1kIrs3G');
INSERT INTO public.users (username, password) VALUES ('Anastasia', '$2a$10$tdBXWNyNDnp0HbnjWtK3g./HquMyK8WUH9sWr937J9AAwW1kIrs3G');

INSERT INTO public.messages(content, receiver, read) VALUES ('XY was cancelled!', 'Anastasia', false);
INSERT INTO public.messages(content, receiver, read) VALUES ('XY meeting date changed to 21.02.2025. :) !', 'Anastasia', false);
INSERT INTO public.messages(content, receiver, read) VALUES ('Attendee Anastasia quit XY!', 'Milenko', false);
INSERT INTO public.messages(content, receiver, read) VALUES ('You have been invited to ZY by Anastasia', 'Milenko', false);

-- !Downs
DROP TABLE users;
DROP TABLE messages;